# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\My_Projects\Temperature-Uart-7.0\src\tiny_uart.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(993, 714)
        MainWindow.setMinimumSize(QtCore.QSize(993, 650))
        MainWindow.setMaximumSize(QtCore.QSize(993, 850))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setMouseTracking(False)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("f:\\My_Projects\\Temperature-Uart-7.0\\src\\../ico/tb.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(0.9)
        MainWindow.setWhatsThis("")
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet("font-family:楷体;\n"
"font-size:14pt;\n"
"font-weight:bold;\n"
"QStatus#statusBar{\n"
"    border-bottom-left-radius:20px;\n"
"    border-bottom-right-radius:20px;\n"
"\n"
"}")
        MainWindow.setInputMethodHints(QtCore.Qt.ImhNone)
        MainWindow.setIconSize(QtCore.QSize(30, 30))
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 951, 651))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("QTabBar::tab{\n"
"    color:black;\n"
"    border-radius:15px;\n"
"}\n"
"QTabBar::tab:hover{\n"
"    background:rgb(255,166,15);\n"
"}\n"
"QTabBar::tab:selected{\n"
"    border-color:rgb(129,60,133);\n"
"    background:rgb(46,49,124);\n"
"    color:white\n"
"}\n"
"\n"
"")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(15, 15))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(30, 40, 271, 351))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox#groupBox{\n"
"    border: 1px solid gray;\n"
"    border-radius:15px;\n"
"}")
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.comboBox_uart = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_uart.setGeometry(QtCore.QRect(0, 30, 271, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.comboBox_uart.setFont(font)
        self.comboBox_uart.setStyleSheet("QComboBox#comboBox_uart{\n"
"    font-family:楷体;\n"
"    font-weight:normal;\n"
"}")
        self.comboBox_uart.setObjectName("comboBox_uart")
        self.pushButton_open = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_open.setGeometry(QtCore.QRect(0, 210, 271, 51))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.pushButton_open.setFont(font)
        self.pushButton_open.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_open.setStyleSheet("QPushButton { border-top:1px solid gray;\n"
"border-bottom:1px solid gray;\n"
"border-left:1px solid graye;\n"
"border-right:1px solid gray;\n"
"border-radius:10px; } \n"
"QPushButton:hover { background-color: rgb(85, 170, 255); }\n"
"QPushButton:pressed { background-color:rgb(129, 60, 133);}\n"
"background:transparent;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("f:\\My_Projects\\Temperature-Uart-7.0\\src\\../ico/ck1.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_open.setIcon(icon1)
        self.pushButton_open.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_open.setObjectName("pushButton_open")
        self.pushButton_refresh = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_refresh.setGeometry(QtCore.QRect(0, 280, 271, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.pushButton_refresh.setFont(font)
        self.pushButton_refresh.setStyleSheet("QPushButton { border-top:1px solid gray;\n"
"border-bottom:1px solid gray;\n"
"border-left:1px solid graye;\n"
"border-right:1px solid gray;\n"
"border-radius:10px; } \n"
"QPushButton:hover { background-color: rgb(85, 170, 255); }\n"
"QPushButton:pressed { background-color:rgb(129, 60, 133);}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("f:\\My_Projects\\Temperature-Uart-7.0\\src\\../ico/sx.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_refresh.setIcon(icon2)
        self.pushButton_refresh.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_refresh.setObjectName("pushButton_refresh")
        self.label_ck = QtWidgets.QLabel(self.groupBox)
        self.label_ck.setGeometry(QtCore.QRect(90, 90, 91, 91))
        self.label_ck.setText("")
        self.label_ck.setPixmap(QtGui.QPixmap("f:\\My_Projects\\Temperature-Uart-7.0\\src\\../ico/connect_no.ico"))
        self.label_ck.setScaledContents(True)
        self.label_ck.setObjectName("label_ck")
        self.rx_lcdNumber = QtWidgets.QLCDNumber(self.tab)
        self.rx_lcdNumber.setGeometry(QtCore.QRect(99, 500, 191, 41))
        self.rx_lcdNumber.setStyleSheet("border-top:1px solid gray;\n"
"border-bottom:1px solid gray;\n"
"border-left:1px solid graye;\n"
"border-right:1px solid gray;\n"
"border-radius:10px;")
        self.rx_lcdNumber.setDigitCount(9)
        self.rx_lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.rx_lcdNumber.setObjectName("rx_lcdNumber")
        self.tx_lcdNumber = QtWidgets.QLCDNumber(self.tab)
        self.tx_lcdNumber.setGeometry(QtCore.QRect(100, 440, 191, 41))
        self.tx_lcdNumber.setStyleSheet("border-top:1px solid gray;\n"
"border-bottom:1px solid gray;\n"
"border-left:1px solid graye;\n"
"border-right:1px solid gray;\n"
"border-radius:10px;")
        self.tx_lcdNumber.setSmallDecimalPoint(False)
        self.tx_lcdNumber.setDigitCount(9)
        self.tx_lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.tx_lcdNumber.setProperty("value", 0.0)
        self.tx_lcdNumber.setProperty("intValue", 0)
        self.tx_lcdNumber.setObjectName("tx_lcdNumber")
        self.tx_lineEdit = QtWidgets.QLineEdit(self.tab)
        self.tx_lineEdit.setGeometry(QtCore.QRect(350, 70, 511, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setKerning(True)
        self.tx_lineEdit.setFont(font)
        self.tx_lineEdit.setStyleSheet("border-radius:15px;\n"
"border:1px solid gray;\n"
"font-family:Consolas;\n"
"font-style:italic;\n"
"font-weight:bold;\n"
"color:rgb(236,45,122);\n"
"background:transparent;")
        self.tx_lineEdit.setObjectName("tx_lineEdit")
        self.rx_textBrowser = QtWidgets.QTextBrowser(self.tab)
        self.rx_textBrowser.setGeometry(QtCore.QRect(350, 350, 571, 161))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setKerning(True)
        self.rx_textBrowser.setFont(font)
        self.rx_textBrowser.setStyleSheet("background-color: rgb(196, 215, 214);\n"
"color: rgb(244, 62, 6);\n"
"border-top:1px solid gray;\n"
"border-bottom:1px solid gray;\n"
"border-left:1px solid graye;\n"
"border-right:1px solid gray;\n"
"font-family:Consolas;\n"
"border-radius:15px;\n"
"background:transparent;\n"
"font-style:italic;\n"
"font-weight:bold;")
        self.rx_textBrowser.setObjectName("rx_textBrowser")
        self.Hex_textBrowser = QtWidgets.QTextBrowser(self.tab)
        self.Hex_textBrowser.setGeometry(QtCore.QRect(350, 120, 571, 111))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setKerning(True)
        self.Hex_textBrowser.setFont(font)
        self.Hex_textBrowser.setStyleSheet("\n"
"color: rgb(15,89,164);\n"
"border-top:1px solid gray;\n"
"border-bottom:1px solid gray;\n"
"border-left:1px solid graye;\n"
"border-right:1px solid gray;\n"
"font-family:Consolas;\n"
"font-style:italic;\n"
"font-weight:bold;\n"
"border-radius:15px;\n"
"background:transparent;")
        self.Hex_textBrowser.setObjectName("Hex_textBrowser")
        self.pushButton_send = QtWidgets.QPushButton(self.tab)
        self.pushButton_send.setGeometry(QtCore.QRect(640, 250, 91, 51))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.pushButton_send.setFont(font)
        self.pushButton_send.setStyleSheet("QPushButton { border-top:1px solid gray;\n"
"border-bottom:1px solid gray;\n"
"border-left:1px solid graye;\n"
"border-right:1px solid gray;\n"
"border-radius:10px; } \n"
"QPushButton:hover { background-color: rgb(85, 170, 255); }\n"
"QPushButton:pressed { background-color:rgb(129, 60, 133);}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("f:\\My_Projects\\Temperature-Uart-7.0\\src\\../ico/fj.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_send.setIcon(icon3)
        self.pushButton_send.setObjectName("pushButton_send")
        self.pushButton_clear_tx = QtWidgets.QPushButton(self.tab)
        self.pushButton_clear_tx.setGeometry(QtCore.QRect(780, 250, 101, 51))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.pushButton_clear_tx.setFont(font)
        self.pushButton_clear_tx.setStyleSheet("QPushButton { border-top:1px solid gray;\n"
"border-bottom:1px solid gray;\n"
"border-left:1px solid graye;\n"
"border-right:1px solid gray;\n"
"border-radius:10px; } \n"
"QPushButton:hover { background-color: rgb(85, 170, 255); }\n"
"QPushButton:pressed { background-color:rgb(129, 60, 133);}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("f:\\My_Projects\\Temperature-Uart-7.0\\src\\../ico/clear.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_clear_tx.setIcon(icon4)
        self.pushButton_clear_tx.setObjectName("pushButton_clear_tx")
        self.pushButton_clear_rx = QtWidgets.QPushButton(self.tab)
        self.pushButton_clear_rx.setGeometry(QtCore.QRect(720, 530, 111, 71))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.pushButton_clear_rx.setFont(font)
        self.pushButton_clear_rx.setAutoFillBackground(False)
        self.pushButton_clear_rx.setStyleSheet("QPushButton { border-top:1px solid gray;\n"
"border-bottom:1px solid gray;\n"
"border-left:1px solid graye;\n"
"border-right:1px solid gray;\n"
"border-radius:10px; } \n"
"QPushButton:hover { background-color: rgb(85, 170, 255); }\n"
"QPushButton:pressed { background-color:rgb(129, 60, 133);}\n"
"\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("f:\\My_Projects\\Temperature-Uart-7.0\\src\\../ico/clear1.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_clear_rx.setIcon(icon5)
        self.pushButton_clear_rx.setCheckable(False)
        self.pushButton_clear_rx.setAutoDefault(False)
        self.pushButton_clear_rx.setDefault(False)
        self.pushButton_clear_rx.setObjectName("pushButton_clear_rx")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(350, 25, 121, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(350, 310, 121, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(40, 450, 36, 24))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font-family:Consolas;\n"
"font-style:italic;\n"
"font-weight:bold;")
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(40, 510, 36, 24))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("font-family:Consolas;\n"
"font-style:italic;\n"
"font-weight:bold;")
        self.label_6.setObjectName("label_6")
        self.checkBox_HexSend = QtWidgets.QCheckBox(self.tab)
        self.checkBox_HexSend.setGeometry(QtCore.QRect(390, 262, 71, 26))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setKerning(True)
        self.checkBox_HexSend.setFont(font)
        self.checkBox_HexSend.setStyleSheet("font-family:Consolas;\n"
"font-style:italic;\n"
"font-weight:bold;")
        self.checkBox_HexSend.setChecked(True)
        self.checkBox_HexSend.setObjectName("checkBox_HexSend")
        self.checkBox_AddEnd = QtWidgets.QCheckBox(self.tab)
        self.checkBox_AddEnd.setEnabled(True)
        self.checkBox_AddEnd.setGeometry(QtCore.QRect(490, 264, 101, 23))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.checkBox_AddEnd.setFont(font)
        self.checkBox_AddEnd.setCheckable(True)
        self.checkBox_AddEnd.setChecked(True)
        self.checkBox_AddEnd.setObjectName("checkBox_AddEnd")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(390, 530, 261, 71))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("QGroupBox#groupBox_2{\n"
"    border: 1px solid gray;\n"
"    border-radius:15px;\n"
"}")
        self.groupBox_2.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_ascii = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_ascii.setGeometry(QtCore.QRect(40, 32, 101, 26))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setKerning(True)
        self.radioButton_ascii.setFont(font)
        self.radioButton_ascii.setStyleSheet("font-family:Consolas;\n"
"font-style:italic;\n"
"font-weight:bold;")
        self.radioButton_ascii.setChecked(True)
        self.radioButton_ascii.setAutoRepeat(False)
        self.radioButton_ascii.setObjectName("radioButton_ascii")
        self.radioButton_hex = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_hex.setGeometry(QtCore.QRect(160, 32, 71, 26))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setKerning(True)
        self.radioButton_hex.setFont(font)
        self.radioButton_hex.setMouseTracking(False)
        self.radioButton_hex.setStyleSheet("font-family:Consolas;\n"
"font-style:italic;\n"
"font-weight:bold;")
        self.radioButton_hex.setChecked(False)
        self.radioButton_hex.setObjectName("radioButton_hex")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(40, 560, 61, 51))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("f:\\My_Projects\\Temperature-Uart-7.0\\src\\../ico/feather.ico"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_22 = QtWidgets.QLabel(self.tab)
        self.label_22.setGeometry(QtCore.QRect(870, 71, 41, 41))
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap("f:\\My_Projects\\Temperature-Uart-7.0\\src\\../ico/maliao.ico"))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(110, 580, 201, 31))
        self.label_11.setStyleSheet("font-family:Consolas;\n"
"font-style:italic;\n"
"font-weight:bold;")
        self.label_11.setObjectName("label_11")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("f:\\My_Projects\\Temperature-Uart-7.0\\src\\../ico/ck.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon6, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tem_set_last_lcdNumber = QtWidgets.QLCDNumber(self.tab_2)
        self.tem_set_last_lcdNumber.setGeometry(QtCore.QRect(790, 480, 71, 31))
        self.tem_set_last_lcdNumber.setStyleSheet("border-top:1px solid gray;\n"
"border-bottom:1px solid gray;\n"
"border-left:1px solid graye;\n"
"border-right:1px solid gray;\n"
"border-radius:10px;")
        self.tem_set_last_lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.tem_set_last_lcdNumber.setObjectName("tem_set_last_lcdNumber")
        self.tem_set_lcdNumber = QtWidgets.QLCDNumber(self.tab_2)
        self.tem_set_lcdNumber.setGeometry(QtCore.QRect(790, 510, 151, 51))
        self.tem_set_lcdNumber.setStyleSheet("border-top:1px solid gray;\n"
"border-bottom:1px solid gray;\n"
"border-left:1px solid graye;\n"
"border-right:1px solid gray;\n"
"color: rgb(255, 0, 0);\n"
"border-radius:10px;")
        self.tem_set_lcdNumber.setSmallDecimalPoint(False)
        self.tem_set_lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.tem_set_lcdNumber.setProperty("value", 0.0)
        self.tem_set_lcdNumber.setProperty("intValue", 0)
        self.tem_set_lcdNumber.setObjectName("tem_set_lcdNumber")
        self.pushButton_tem_set = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_tem_set.setGeometry(QtCore.QRect(790, 430, 151, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.pushButton_tem_set.setFont(font)
        self.pushButton_tem_set.setStyleSheet("QPushButton { border-top:1px solid gray;\n"
"border-bottom:1px solid gray;\n"
"border-left:1px solid graye;\n"
"border-right:1px solid gray;\n"
" border-radius:10px;} \n"
"QPushButton:hover { background-color: rgb(85, 170, 255); }\n"
"QPushButton:pressed { background-color:rgb(129, 60, 133);}\n"
"")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("f:\\My_Projects\\Temperature-Uart-7.0\\src\\../ico/tem.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_tem_set.setIcon(icon7)
        self.pushButton_tem_set.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_tem_set.setObjectName("pushButton_tem_set")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.doubleSpinBox.setGeometry(QtCore.QRect(860, 470, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.doubleSpinBox.setFont(font)
        self.doubleSpinBox.setStyleSheet("font-family:Consolas;\n"
"font-weight:bold;\n"
"color: red;\n"
"border-top:1px solid gray;\n"
"border-bottom:1px solid gray;\n"
"border-left:1px solid graye;\n"
"border-right:1px solid gray;\n"
"background:transparent;\n"
"border-radius:15px;")
        self.doubleSpinBox.setMinimum(15.0)
        self.doubleSpinBox.setMaximum(50.0)
        self.doubleSpinBox.setSingleStep(0.01)
        self.doubleSpinBox.setProperty("value", 25.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.tem_real_lcdNumber = QtWidgets.QLCDNumber(self.tab_2)
        self.tem_real_lcdNumber.setGeometry(QtCore.QRect(790, 350, 151, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(14, 176, 201))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(14, 176, 201))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(14, 176, 201))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(14, 176, 201))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(14, 176, 201))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(14, 176, 201))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(14, 176, 201))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(14, 176, 201))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(14, 176, 201))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.tem_real_lcdNumber.setPalette(palette)
        self.tem_real_lcdNumber.setStyleSheet("border-top:1px solid gray;\n"
"border-bottom:1px solid gray;\n"
"border-left:1px solid graye;\n"
"border-right:1px solid gray;\n"
"color: rgb(14, 176, 201);\n"
"border-radius:10px;")
        self.tem_real_lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.tem_real_lcdNumber.setProperty("value", 0.0)
        self.tem_real_lcdNumber.setProperty("intValue", 0)
        self.tem_real_lcdNumber.setObjectName("tem_real_lcdNumber")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(800, 280, 131, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 280, 771, 291))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_plotwidget = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_plotwidget.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_plotwidget.setObjectName("horizontalLayout_plotwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 39, 931, 231))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_note = QtWidgets.QLabel(self.tab_2)
        self.label_note.setGeometry(QtCore.QRect(10, 10, 541, 21))
        self.label_note.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_note.setStyleSheet("font-family:Consolas;\n"
"font-style:italic;\n"
"font-weight:bold;\n"
"color: rgb(155, 30, 100);")
        self.label_note.setAlignment(QtCore.Qt.AlignCenter)
        self.label_note.setObjectName("label_note")
        self.label_sub = QtWidgets.QLabel(self.tab_2)
        self.label_sub.setGeometry(QtCore.QRect(580, 10, 361, 21))
        self.label_sub.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_sub.setStyleSheet("font-family:Consolas;\n"
"font-style:italic;\n"
"font-weight:bold;\n"
"color: rgb(155, 30, 100);")
        self.label_sub.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sub.setObjectName("label_sub")
        self.pushButton_save = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_save.setGeometry(QtCore.QRect(340, 580, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setKerning(True)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setStyleSheet("QPushButton { border-top:1px solid gray;\n"
"border-bottom:1px solid gray;\n"
"border-left:1px solid graye;\n"
"border-right:1px solid gray;\n"
"border-radius:10px;\n"
"font-family:Consolas;\n"
"font-style:italic;\n"
"font-weight:bold;\n"
"color: rgb(155, 30, 100);\n"
" } \n"
"QPushButton:hover { background-color: rgb(85, 170, 255); }\n"
"QPushButton:pressed { background-color:rgb(129, 60, 133);}")
        self.pushButton_save.setCheckable(True)
        self.pushButton_save.setChecked(False)
        self.pushButton_save.setAutoExclusive(True)
        self.pushButton_save.setObjectName("pushButton_save")
        self.pushButton_draw = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_draw.setGeometry(QtCore.QRect(150, 580, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setKerning(True)
        self.pushButton_draw.setFont(font)
        self.pushButton_draw.setStyleSheet("QPushButton { border-top:1px solid gray;\n"
"border-bottom:1px solid gray;\n"
"border-left:1px solid graye;\n"
"border-right:1px solid gray;\n"
"border-radius:10px;\n"
"font-family:Consolas;\n"
"font-style:italic;\n"
"font-weight:bold;\n"
"color: rgb(155, 30, 100);\n"
" } \n"
"QPushButton:hover { background-color: rgb(85, 170, 255); }\n"
"QPushButton:pressed { background-color:rgb(129, 60, 133);}")
        self.pushButton_draw.setCheckable(True)
        self.pushButton_draw.setChecked(False)
        self.pushButton_draw.setAutoExclusive(True)
        self.pushButton_draw.setObjectName("pushButton_draw")
        self.pushButton_clear = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_clear.setGeometry(QtCore.QRect(530, 580, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setKerning(True)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setStyleSheet("QPushButton { border-top:1px solid gray;\n"
"border-bottom:1px solid gray;\n"
"border-left:1px solid graye;\n"
"border-right:1px solid gray;\n"
"border-radius:10px;\n"
"font-family:Consolas;\n"
"font-style:italic;\n"
"font-weight:bold;\n"
"color: rgb(155, 30, 100);\n"
" } \n"
"QPushButton:hover { background-color: rgb(85, 170, 255); }\n"
"QPushButton:pressed { background-color:rgb(129, 60, 133);}")
        self.pushButton_clear.setCheckable(True)
        self.pushButton_clear.setChecked(True)
        self.pushButton_clear.setAutoExclusive(True)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.pushButton_start = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_start.setGeometry(QtCore.QRect(791, 315, 71, 30))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setStyleSheet("QPushButton { border-top:1px solid gray;\n"
"border-bottom:1px solid gray;\n"
"border-left:1px solid graye;\n"
"border-right:1px solid gray;\n"
"border-radius:10px;\n"
"font-family:Consolas;\n"
"font-style:italic;\n"
"font-weight:bold;\n"
" } \n"
"QPushButton:hover { background-color: rgb(85, 170, 255); }\n"
"QPushButton:pressed { background-color:rgb(129, 60, 133);}")
        self.pushButton_start.setCheckable(True)
        self.pushButton_start.setChecked(False)
        self.pushButton_start.setAutoExclusive(True)
        self.pushButton_start.setObjectName("pushButton_start")
        self.pushButton_stop = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_stop.setGeometry(QtCore.QRect(870, 315, 71, 30))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setKerning(True)
        self.pushButton_stop.setFont(font)
        self.pushButton_stop.setStyleSheet("QPushButton { border-top:1px solid gray;\n"
"border-bottom:1px solid gray;\n"
"border-left:1px solid graye;\n"
"border-right:1px solid gray;\n"
"border-radius:10px;\n"
"font-family:Consolas;\n"
"font-style:italic;\n"
"font-weight:bold;\n"
" } \n"
"QPushButton:hover { background-color: rgb(85, 170, 255); }\n"
"QPushButton:pressed { background-color:rgb(129, 60, 133);}")
        self.pushButton_stop.setCheckable(True)
        self.pushButton_stop.setChecked(True)
        self.pushButton_stop.setAutoExclusive(True)
        self.pushButton_stop.setObjectName("pushButton_stop")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("f:\\My_Projects\\Temperature-Uart-7.0\\src\\../ico/zhexian.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_2, icon8, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab_4)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 40, 711, 531))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_cycle = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_cycle.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_cycle.setObjectName("horizontalLayout_cycle")
        self.pushButton_cycle = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_cycle.setGeometry(QtCore.QRect(730, 320, 211, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.pushButton_cycle.setFont(font)
        self.pushButton_cycle.setStyleSheet("QPushButton { border-top:1px solid gray;\n"
"border-bottom:1px solid gray;\n"
"border-left:1px solid graye;\n"
"border-right:1px solid gray;\n"
" border-radius:10px;} \n"
"QPushButton:hover { background-color: rgb(85, 170, 255); }\n"
"QPushButton:pressed { background-color:rgb(129, 60, 133);}\n"
"")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("f:\\My_Projects\\Temperature-Uart-7.0\\src\\../ico/sd.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_cycle.setIcon(icon9)
        self.pushButton_cycle.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_cycle.setObjectName("pushButton_cycle")
        self.groupBox_cycle = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_cycle.setGeometry(QtCore.QRect(730, 20, 211, 281))
        self.groupBox_cycle.setStyleSheet("QGroupBox#groupBox_cycle{\n"
"    border: 1px solid gray;\n"
"    border-radius:15px;\n"
"}")
        self.groupBox_cycle.setObjectName("groupBox_cycle")
        self.label_14 = QtWidgets.QLabel(self.groupBox_cycle)
        self.label_14.setGeometry(QtCore.QRect(60, 30, 71, 21))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_cycle)
        self.label_15.setGeometry(QtCore.QRect(60, 70, 71, 21))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.slider_tem_1 = QtWidgets.QSlider(self.groupBox_cycle)
        self.slider_tem_1.setEnabled(True)
        self.slider_tem_1.setGeometry(QtCore.QRect(50, 50, 151, 20))
        self.slider_tem_1.setAutoFillBackground(False)
        self.slider_tem_1.setStyleSheet("QSlider::groove:horizontal{ \n"
"     height: 12px; \n"
"     left: 0px; \n"
"     right: 0px; \n"
"     border:0px;   \n"
"     border-radius:6px;   \n"
"     background:rgba(0,0,0,50);\n"
" } \n"
"QSlider::handle:horizontal{ \n"
"       width:  10px; \n"
"       height: 5px; \n"
"      margin-top: -2px; \n"
"   \n"
"      margin-bottom: -2px; \n"
"    margin-left: 0px; \n"
"        margin-right: 0px; \n"
"        background:rgba(252,140,35,1);\n"
" } \n"
"\n"
"QSlider::sub-page:horizontal{\n"
"       background:rgba(80,166,234,1);\n"
" }")
        self.slider_tem_1.setMinimum(10)
        self.slider_tem_1.setMaximum(200)
        self.slider_tem_1.setSingleStep(1)
        self.slider_tem_1.setOrientation(QtCore.Qt.Horizontal)
        self.slider_tem_1.setObjectName("slider_tem_1")
        self.slider_tem_2 = QtWidgets.QSlider(self.groupBox_cycle)
        self.slider_tem_2.setEnabled(False)
        self.slider_tem_2.setGeometry(QtCore.QRect(50, 90, 151, 20))
        self.slider_tem_2.setStyleSheet("QSlider::groove:horizontal{ \n"
"     height: 12px; \n"
"     left: 0px; \n"
"     right: 0px; \n"
"     border:0px;   \n"
"     border-radius:6px;   \n"
"     background:rgba(0,0,0,50);\n"
" } \n"
"QSlider::handle:horizontal{ \n"
"       width:  10px; \n"
"       height: 5px; \n"
"      margin-top: -2px; \n"
"       margin-left: 0px; \n"
"      margin-bottom: -2px; \n"
"        margin-right: 0px; \n"
"        background:gray;\n"
" } \n"
"\n"
"QSlider::sub-page:horizontal{\n"
"       background:rgba(80,166,234,1);\n"
" }")
        self.slider_tem_2.setMinimum(10)
        self.slider_tem_2.setMaximum(200)
        self.slider_tem_2.setOrientation(QtCore.Qt.Horizontal)
        self.slider_tem_2.setObjectName("slider_tem_2")
        self.label_17 = QtWidgets.QLabel(self.groupBox_cycle)
        self.label_17.setGeometry(QtCore.QRect(60, 210, 91, 21))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.label_tem_1 = QtWidgets.QLabel(self.groupBox_cycle)
        self.label_tem_1.setGeometry(QtCore.QRect(140, 30, 51, 21))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_tem_1.setFont(font)
        self.label_tem_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tem_1.setObjectName("label_tem_1")
        self.label_tem_2 = QtWidgets.QLabel(self.groupBox_cycle)
        self.label_tem_2.setGeometry(QtCore.QRect(140, 70, 51, 21))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_tem_2.setFont(font)
        self.label_tem_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tem_2.setObjectName("label_tem_2")
        self.slider_number = QtWidgets.QSlider(self.groupBox_cycle)
        self.slider_number.setGeometry(QtCore.QRect(10, 50, 22, 141))
        self.slider_number.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.slider_number.setStyleSheet("QSlider::groove:vertical{ \n"
" \n"
"     background:rgba(0,0,0,50);\n"
" } \n"
"QSlider::handle:vertical{ \n"
"\n"
"     width:  10px; \n"
"       height: 15px; \n"
"        background:green;\n"
" } \n"
"\n"
"QSlider::sub-page:vertical{\n"
"       background:rgba(80,166,234,1);\n"
" }")
        self.slider_number.setMinimum(1)
        self.slider_number.setMaximum(4)
        self.slider_number.setProperty("value", 1)
        self.slider_number.setSliderPosition(1)
        self.slider_number.setTracking(True)
        self.slider_number.setOrientation(QtCore.Qt.Vertical)
        self.slider_number.setInvertedAppearance(True)
        self.slider_number.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.slider_number.setObjectName("slider_number")
        self.slider_tem_3 = QtWidgets.QSlider(self.groupBox_cycle)
        self.slider_tem_3.setEnabled(False)
        self.slider_tem_3.setGeometry(QtCore.QRect(50, 130, 151, 20))
        self.slider_tem_3.setStyleSheet("QSlider::groove:horizontal{ \n"
"     height: 12px; \n"
"     left: 0px; \n"
"     right: 0px; \n"
"     border:0px;   \n"
"     border-radius:6px;   \n"
"     background:rgba(0,0,0,50);\n"
" } \n"
"QSlider::handle:horizontal{ \n"
"       width:  10px; \n"
"       height: 5px; \n"
"      margin-top: -2px; \n"
"       margin-left: 0px; \n"
"      margin-bottom: -2px; \n"
"        margin-right: 0px; \n"
"        background:gray;\n"
" } \n"
"\n"
"QSlider::sub-page:horizontal{\n"
"       background:rgba(80,166,234,1);\n"
" }")
        self.slider_tem_3.setMinimum(10)
        self.slider_tem_3.setMaximum(200)
        self.slider_tem_3.setOrientation(QtCore.Qt.Horizontal)
        self.slider_tem_3.setObjectName("slider_tem_3")
        self.label_tem_3 = QtWidgets.QLabel(self.groupBox_cycle)
        self.label_tem_3.setGeometry(QtCore.QRect(140, 110, 51, 21))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_tem_3.setFont(font)
        self.label_tem_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tem_3.setObjectName("label_tem_3")
        self.label_19 = QtWidgets.QLabel(self.groupBox_cycle)
        self.label_19.setGeometry(QtCore.QRect(60, 110, 71, 21))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_cycle)
        self.label_20.setGeometry(QtCore.QRect(60, 150, 71, 21))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.slider_tem_4 = QtWidgets.QSlider(self.groupBox_cycle)
        self.slider_tem_4.setEnabled(False)
        self.slider_tem_4.setGeometry(QtCore.QRect(50, 170, 151, 20))
        self.slider_tem_4.setStyleSheet("QSlider::groove:horizontal{ \n"
"     height: 12px; \n"
"     left: 0px; \n"
"     right: 0px; \n"
"     border:0px;   \n"
"     border-radius:6px;   \n"
"     background:rgba(0,0,0,50);\n"
" } \n"
"QSlider::handle:horizontal{ \n"
"       width:  10px; \n"
"       height: 5px; \n"
"      margin-top: -2px; \n"
"       margin-left: 0px; \n"
"      margin-bottom: -2px; \n"
"        margin-right: 0px; \n"
"        background:gray;\n"
" } \n"
"\n"
"QSlider::sub-page:horizontal{\n"
"       background:rgba(80,166,234,1);\n"
" }")
        self.slider_tem_4.setMinimum(10)
        self.slider_tem_4.setMaximum(200)
        self.slider_tem_4.setOrientation(QtCore.Qt.Horizontal)
        self.slider_tem_4.setObjectName("slider_tem_4")
        self.label_tem_4 = QtWidgets.QLabel(self.groupBox_cycle)
        self.label_tem_4.setGeometry(QtCore.QRect(140, 150, 51, 21))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_tem_4.setFont(font)
        self.label_tem_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tem_4.setObjectName("label_tem_4")
        self.slider_time = QtWidgets.QSlider(self.groupBox_cycle)
        self.slider_time.setGeometry(QtCore.QRect(10, 230, 191, 20))
        self.slider_time.setStyleSheet("QSlider::groove:horizontal{ \n"
"     height: 12px; \n"
"     left: 0px; \n"
"     right: 0px; \n"
"     border:0px;   \n"
"     border-radius:6px;   \n"
"     background:rgba(0,0,0,50);\n"
" } \n"
"QSlider::handle:horizontal{ \n"
"       width:  10px; \n"
"       height: 5px; \n"
"      margin-top: -2px; \n"
"   \n"
"      margin-bottom: -2px; \n"
"    margin-left: 0px; \n"
"        margin-right: 0px; \n"
"        background:rgba(126,22,113,1);\n"
" } \n"
"\n"
"QSlider::sub-page:horizontal{\n"
"       background:rgba(80,166,234,1);\n"
" }")
        self.slider_time.setMinimum(10)
        self.slider_time.setMaximum(120)
        self.slider_time.setProperty("value", 10)
        self.slider_time.setOrientation(QtCore.Qt.Horizontal)
        self.slider_time.setObjectName("slider_time")
        self.label_time = QtWidgets.QLabel(self.groupBox_cycle)
        self.label_time.setGeometry(QtCore.QRect(60, 250, 91, 21))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_time.setFont(font)
        self.label_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time.setObjectName("label_time")
        self.label_18 = QtWidgets.QLabel(self.tab_4)
        self.label_18.setGeometry(QtCore.QRect(740, 400, 111, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: rgb(67, 178, 68);")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_21 = QtWidgets.QLabel(self.tab_4)
        self.label_21.setGeometry(QtCore.QRect(740, 440, 111, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("\n"
"color: rgb(255, 0, 0);")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.label_real_tem = QtWidgets.QLabel(self.tab_4)
        self.label_real_tem.setGeometry(QtCore.QRect(850, 400, 51, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_real_tem.setFont(font)
        self.label_real_tem.setStyleSheet("color: rgb(67, 178, 68);")
        self.label_real_tem.setAlignment(QtCore.Qt.AlignCenter)
        self.label_real_tem.setObjectName("label_real_tem")
        self.label_set_tem = QtWidgets.QLabel(self.tab_4)
        self.label_set_tem.setGeometry(QtCore.QRect(850, 440, 51, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_set_tem.setFont(font)
        self.label_set_tem.setStyleSheet("\n"
"color: rgb(255, 0, 0);")
        self.label_set_tem.setAlignment(QtCore.Qt.AlignCenter)
        self.label_set_tem.setObjectName("label_set_tem")
        self.pushButton_cycle_start = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_cycle_start.setGeometry(QtCore.QRect(741, 500, 81, 51))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.pushButton_cycle_start.setFont(font)
        self.pushButton_cycle_start.setAutoFillBackground(False)
        self.pushButton_cycle_start.setStyleSheet("QPushButton { border-top:1px solid gray;\n"
"border-bottom:1px solid gray;\n"
"border-left:1px solid graye;\n"
"border-right:1px solid gray;\n"
"border-radius:10px;\n"
"\n"
" } \n"
"QPushButton:hover { background-color: rgb(85, 170, 255); }\n"
"QPushButton:pressed { background-color:rgb(129, 60, 133);}\n"
"\n"
"")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("f:\\My_Projects\\Temperature-Uart-7.0\\src\\../ico/ks.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_cycle_start.setIcon(icon10)
        self.pushButton_cycle_start.setCheckable(False)
        self.pushButton_cycle_start.setAutoDefault(False)
        self.pushButton_cycle_start.setDefault(False)
        self.pushButton_cycle_start.setObjectName("pushButton_cycle_start")
        self.pushButton_cycle_stop = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_cycle_stop.setGeometry(QtCore.QRect(842, 500, 81, 51))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.pushButton_cycle_stop.setFont(font)
        self.pushButton_cycle_stop.setAutoFillBackground(False)
        self.pushButton_cycle_stop.setStyleSheet("QPushButton { border-top:1px solid gray;\n"
"border-bottom:1px solid gray;\n"
"border-left:1px solid graye;\n"
"border-right:1px solid gray;\n"
"border-radius:10px; } \n"
"QPushButton:hover { background-color: rgb(85, 170, 255); }\n"
"QPushButton:pressed { background-color:rgb(129, 60, 133);}\n"
"\n"
"")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("f:\\My_Projects\\Temperature-Uart-7.0\\src\\../ico/tingzhi.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_cycle_stop.setIcon(icon11)
        self.pushButton_cycle_stop.setCheckable(False)
        self.pushButton_cycle_stop.setChecked(False)
        self.pushButton_cycle_stop.setAutoDefault(False)
        self.pushButton_cycle_stop.setDefault(False)
        self.pushButton_cycle_stop.setObjectName("pushButton_cycle_stop")
        self.label_real_tem_2 = QtWidgets.QLabel(self.tab_4)
        self.label_real_tem_2.setGeometry(QtCore.QRect(900, 400, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_real_tem_2.setFont(font)
        self.label_real_tem_2.setStyleSheet("font-family:Consolas;\n"
"font-style:italic;\n"
"font-weight:bold;\n"
"color: rgb(67, 178, 68);")
        self.label_real_tem_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_real_tem_2.setObjectName("label_real_tem_2")
        self.label_real_tem_3 = QtWidgets.QLabel(self.tab_4)
        self.label_real_tem_3.setGeometry(QtCore.QRect(900, 440, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_real_tem_3.setFont(font)
        self.label_real_tem_3.setStyleSheet("font-family:Consolas;\n"
"font-style:italic;\n"
"font-weight:bold;\n"
"color: rgb(255, 0, 0);")
        self.label_real_tem_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_real_tem_3.setObjectName("label_real_tem_3")
        self.label_note_cycle = QtWidgets.QLabel(self.tab_4)
        self.label_note_cycle.setGeometry(QtCore.QRect(10, 10, 711, 21))
        self.label_note_cycle.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_note_cycle.setStyleSheet("font-family:Consolas;\n"
"font-style:italic;\n"
"font-weight:bold;\n"
"color: rgb(155, 30, 100);")
        self.label_note_cycle.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_note_cycle.setObjectName("label_note_cycle")
        self.pushButton_draw_cycle = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_draw_cycle.setGeometry(QtCore.QRect(150, 580, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setKerning(True)
        self.pushButton_draw_cycle.setFont(font)
        self.pushButton_draw_cycle.setStyleSheet("QPushButton { border-top:1px solid gray;\n"
"border-bottom:1px solid gray;\n"
"border-left:1px solid graye;\n"
"border-right:1px solid gray;\n"
"border-radius:10px;\n"
"font-family:Consolas;\n"
"font-style:italic;\n"
"font-weight:bold;\n"
"color: rgb(155, 30, 100);\n"
" } \n"
"QPushButton:hover { background-color: rgb(85, 170, 255); }\n"
"QPushButton:pressed { background-color:rgb(129, 60, 133);}")
        self.pushButton_draw_cycle.setCheckable(True)
        self.pushButton_draw_cycle.setChecked(False)
        self.pushButton_draw_cycle.setAutoExclusive(True)
        self.pushButton_draw_cycle.setObjectName("pushButton_draw_cycle")
        self.pushButton_save_cycle = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_save_cycle.setGeometry(QtCore.QRect(340, 580, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setKerning(True)
        self.pushButton_save_cycle.setFont(font)
        self.pushButton_save_cycle.setStyleSheet("QPushButton { border-top:1px solid gray;\n"
"border-bottom:1px solid gray;\n"
"border-left:1px solid graye;\n"
"border-right:1px solid gray;\n"
"border-radius:10px;\n"
"font-family:Consolas;\n"
"font-style:italic;\n"
"font-weight:bold;\n"
"color: rgb(155, 30, 100);\n"
" } \n"
"QPushButton:hover { background-color: rgb(85, 170, 255); }\n"
"QPushButton:pressed { background-color:rgb(129, 60, 133);}\n"
"")
        self.pushButton_save_cycle.setCheckable(True)
        self.pushButton_save_cycle.setChecked(False)
        self.pushButton_save_cycle.setAutoExclusive(True)
        self.pushButton_save_cycle.setObjectName("pushButton_save_cycle")
        self.pushButton_clear_cycle = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_clear_cycle.setGeometry(QtCore.QRect(530, 580, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setKerning(True)
        self.pushButton_clear_cycle.setFont(font)
        self.pushButton_clear_cycle.setStyleSheet("QPushButton { border-top:1px solid gray;\n"
"border-bottom:1px solid gray;\n"
"border-left:1px solid graye;\n"
"border-right:1px solid gray;\n"
"border-radius:10px;\n"
"font-family:Consolas;\n"
"font-style:italic;\n"
"font-weight:bold;\n"
"color: rgb(155, 30, 100);\n"
" } \n"
"QPushButton:hover { background-color: rgb(85, 170, 255); }\n"
"QPushButton:pressed { background-color:rgb(129, 60, 133);}")
        self.pushButton_clear_cycle.setCheckable(True)
        self.pushButton_clear_cycle.setChecked(True)
        self.pushButton_clear_cycle.setAutoExclusive(True)
        self.pushButton_clear_cycle.setObjectName("pushButton_clear_cycle")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("f:\\My_Projects\\Temperature-Uart-7.0\\src\\../ico/lianxu.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_4, icon12, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setGeometry(QtCore.QRect(50, 60, 81, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setGeometry(QtCore.QRect(50, 120, 71, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(50, 180, 71, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setGeometry(QtCore.QRect(50, 240, 71, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_datetime = QtWidgets.QLabel(self.tab_3)
        self.label_datetime.setGeometry(QtCore.QRect(510, 590, 111, 21))
        self.label_datetime.setStyleSheet("font-family:楷体;\n"
"font-weight:bold;\n"
"font-size:15px;\n"
"color:white;\n"
"border-bottom-right-radius:20px;")
        self.label_datetime.setObjectName("label_datetime")
        self.label_space2 = QtWidgets.QLabel(self.tab_3)
        self.label_space2.setGeometry(QtCore.QRect(500, 550, 91, 16))
        self.label_space2.setStyleSheet("font-family:Consolas;\n"
"font-weight:bold;\n"
"font-size:15px;\n"
"font-style:italic;\n"
"color:white;")
        self.label_space2.setObjectName("label_space2")
        self.progressBar = QtWidgets.QProgressBar(self.tab_3)
        self.progressBar.setGeometry(QtCore.QRect(640, 550, 191, 21))
        self.progressBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar.setAutoFillBackground(False)
        self.progressBar.setStyleSheet("font-family:楷体;\n"
"font-weight:bold;\n"
"font-size:15px;\n"
"border:none;\n"
"")
        self.progressBar.setProperty("value", 100)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.label_space1 = QtWidgets.QLabel(self.tab_3)
        self.label_space1.setGeometry(QtCore.QRect(390, 550, 91, 16))
        self.label_space1.setStyleSheet("font-family:楷体;\n"
"font-weight:bold;\n"
"font-size:15px;")
        self.label_space1.setObjectName("label_space1")
        self.comboBox_baud = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_baud.setGeometry(QtCore.QRect(180, 50, 151, 41))
        self.comboBox_baud.setObjectName("comboBox_baud")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_data = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_data.setGeometry(QtCore.QRect(180, 111, 151, 41))
        self.comboBox_data.setObjectName("comboBox_data")
        self.comboBox_data.addItem("")
        self.comboBox_data.addItem("")
        self.comboBox_data.addItem("")
        self.comboBox_data.addItem("")
        self.comboBox_check = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_check.setGeometry(QtCore.QRect(178, 171, 151, 41))
        self.comboBox_check.setObjectName("comboBox_check")
        self.comboBox_check.addItem("")
        self.comboBox_check.addItem("")
        self.comboBox_check.addItem("")
        self.comboBox_stop = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_stop.setGeometry(QtCore.QRect(180, 231, 151, 41))
        self.comboBox_stop.setObjectName("comboBox_stop")
        self.comboBox_stop.addItem("")
        self.comboBox_stop.addItem("")
        self.comboBox_stop.addItem("")
        self.label_main_id = QtWidgets.QLabel(self.tab_3)
        self.label_main_id.setGeometry(QtCore.QRect(50, 320, 241, 22))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_main_id.setFont(font)
        self.label_main_id.setStyleSheet("color:rgb(208,16,76);\n"
"font-family:Consolas;\n"
"font-style:italic;\n"
"font-weight:bold;")
        self.label_main_id.setObjectName("label_main_id")
        self.label_serial_id = QtWidgets.QLabel(self.tab_3)
        self.label_serial_id.setGeometry(QtCore.QRect(50, 360, 241, 22))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_serial_id.setFont(font)
        self.label_serial_id.setStyleSheet("color:rgb(208,16,76);\n"
"font-family:Consolas;\n"
"font-style:italic;\n"
"font-weight:bold;")
        self.label_serial_id.setObjectName("label_serial_id")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("f:\\My_Projects\\Temperature-Uart-7.0\\src\\../ico/set1.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_3, icon13, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 993, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.menuBar.sizePolicy().hasHeightForWidth())
        self.menuBar.setSizePolicy(sizePolicy)
        self.menuBar.setStyleSheet("text-align:center\n"
"\n"
"    ")
        self.menuBar.setDefaultUp(False)
        self.menuBar.setNativeMenuBar(True)
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menuBar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        self.toolBar.setAutoFillBackground(False)
        self.toolBar.setStyleSheet("background-color:rgb(83,157,186)")
        self.toolBar.setAllowedAreas(QtCore.Qt.AllToolBarAreas)
        self.toolBar.setIconSize(QtCore.QSize(30, 40))
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setEnabled(True)
        self.statusBar.setMinimumSize(QtCore.QSize(993, 0))
        self.statusBar.setMaximumSize(QtCore.QSize(993, 16777215))
        self.statusBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.statusBar.setAutoFillBackground(False)
        self.statusBar.setStyleSheet("font-family:Consolas;\n"
"font-weight:bold;\n"
"background:rgb(46,49,124);\n"
"\n"
"")
        self.statusBar.setInputMethodHints(QtCore.Qt.ImhDialableCharactersOnly)
        self.statusBar.setSizeGripEnabled(False)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.action_sysm = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("f:\\My_Projects\\Temperature-Uart-7.0\\src\\../ico/shouce.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_sysm.setIcon(icon14)
        self.action_sysm.setObjectName("action_sysm")
        self.action_zzjs = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("f:\\My_Projects\\Temperature-Uart-7.0\\src\\../ico/ak.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_zzjs.setIcon(icon15)
        self.action_zzjs.setObjectName("action_zzjs")
        self.action_zlcx = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("f:\\My_Projects\\Temperature-Uart-7.0\\src\\../ico/find.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_zlcx.setIcon(icon16)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.action_zlcx.setFont(font)
        self.action_zlcx.setObjectName("action_zlcx")
        self.action_set = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("f:\\My_Projects\\Temperature-Uart-7.0\\src\\../ico/shezhi2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_set.setIcon(icon17)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.action_set.setFont(font)
        self.action_set.setObjectName("action_set")
        self.action_sx = QtWidgets.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("f:\\My_Projects\\Temperature-Uart-7.0\\src\\../ico/shuaxin.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_sx.setIcon(icon18)
        self.action_sx.setObjectName("action_sx")
        self.action_alter_theme = QtWidgets.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("f:\\My_Projects\\Temperature-Uart-7.0\\src\\../ico/moon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_alter_theme.setIcon(icon19)
        self.action_alter_theme.setObjectName("action_alter_theme")
        self.action_data = QtWidgets.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap("f:\\My_Projects\\Temperature-Uart-7.0\\src\\../ico/file.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_data.setIcon(icon20)
        self.action_data.setObjectName("action_data")
        self.menu.addAction(self.action_set)
        self.menu.addAction(self.action_sx)
        self.menu.addAction(self.action_alter_theme)
        self.menu_2.addAction(self.action_zlcx)
        self.menu_3.addAction(self.action_sysm)
        self.menu_3.addAction(self.action_zzjs)
        self.menu_3.addAction(self.action_data)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())
        self.menuBar.addAction(self.menu_3.menuAction())
        self.toolBar.addAction(self.action_set)
        self.toolBar.addAction(self.action_sx)
        self.toolBar.addAction(self.action_alter_theme)
        self.toolBar.addAction(self.action_zlcx)
        self.toolBar.addAction(self.action_data)
        self.toolBar.addAction(self.action_sysm)
        self.toolBar.addAction(self.action_zzjs)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tiny Uart V7.0.0"))
        self.groupBox.setTitle(_translate("MainWindow", "串口选择"))
        self.pushButton_open.setText(_translate("MainWindow", "打开串口"))
        self.pushButton_refresh.setText(_translate("MainWindow", "刷新串口"))
        self.rx_textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:14pt; font-weight:600; font-style:italic;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\"><br /></p></body></html>"))
        self.pushButton_send.setText(_translate("MainWindow", "发  送"))
        self.pushButton_clear_tx.setText(_translate("MainWindow", "清空发送"))
        self.pushButton_clear_rx.setText(_translate("MainWindow", "清空接收"))
        self.label_7.setText(_translate("MainWindow", "指令发送框："))
        self.label_8.setText(_translate("MainWindow", "指令接收框："))
        self.label_2.setText(_translate("MainWindow", "TX:"))
        self.label_6.setText(_translate("MainWindow", "RX:"))
        self.checkBox_HexSend.setText(_translate("MainWindow", "HEX"))
        self.checkBox_AddEnd.setText(_translate("MainWindow", "结束符"))
        self.groupBox_2.setTitle(_translate("MainWindow", "接收格式"))
        self.radioButton_ascii.setText(_translate("MainWindow", "ASCII"))
        self.radioButton_hex.setText(_translate("MainWindow", "HEX"))
        self.label_11.setText(_translate("MainWindow", "Created by WangJian"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "指令收发 "))
        self.pushButton_tem_set.setText(_translate("MainWindow", "温度设定"))
        self.label_9.setText(_translate("MainWindow", "实时温度查询"))
        self.label_note.setText(_translate("MainWindow", "Waiting......"))
        self.label_sub.setText(_translate("MainWindow", "Waiting......"))
        self.pushButton_save.setText(_translate("MainWindow", "Save"))
        self.pushButton_draw.setText(_translate("MainWindow", "Draw"))
        self.pushButton_clear.setText(_translate("MainWindow", "Clear"))
        self.pushButton_start.setText(_translate("MainWindow", "Start"))
        self.pushButton_stop.setText(_translate("MainWindow", "Stop"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "单次温度设置"))
        self.pushButton_cycle.setText(_translate("MainWindow", "确认设定"))
        self.groupBox_cycle.setTitle(_translate("MainWindow", "连续设置"))
        self.label_14.setText(_translate("MainWindow", "温度一:"))
        self.label_15.setText(_translate("MainWindow", "温度二:"))
        self.label_17.setText(_translate("MainWindow", "停留时间"))
        self.label_tem_1.setText(_translate("MainWindow", "20℃"))
        self.label_tem_2.setText(_translate("MainWindow", "..."))
        self.label_tem_3.setText(_translate("MainWindow", "..."))
        self.label_19.setText(_translate("MainWindow", "温度三:"))
        self.label_20.setText(_translate("MainWindow", "温度四:"))
        self.label_tem_4.setText(_translate("MainWindow", "..."))
        self.label_time.setText(_translate("MainWindow", "10s"))
        self.label_18.setText(_translate("MainWindow", "实时温度:"))
        self.label_21.setText(_translate("MainWindow", "设定温度:"))
        self.label_real_tem.setText(_translate("MainWindow", "0"))
        self.label_set_tem.setText(_translate("MainWindow", "0"))
        self.pushButton_cycle_start.setText(_translate("MainWindow", "开始"))
        self.pushButton_cycle_stop.setText(_translate("MainWindow", "停止"))
        self.label_real_tem_2.setText(_translate("MainWindow", "℃"))
        self.label_real_tem_3.setText(_translate("MainWindow", "℃"))
        self.label_note_cycle.setText(_translate("MainWindow", "Waiting......"))
        self.pushButton_draw_cycle.setText(_translate("MainWindow", "Draw"))
        self.pushButton_save_cycle.setText(_translate("MainWindow", "Save"))
        self.pushButton_clear_cycle.setText(_translate("MainWindow", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "连续温度设置"))
        self.label_4.setText(_translate("MainWindow", "波特率"))
        self.label.setText(_translate("MainWindow", "数据位"))
        self.label_3.setText(_translate("MainWindow", "校验位"))
        self.label_5.setText(_translate("MainWindow", "停止位"))
        self.label_datetime.setText(_translate("MainWindow", "TextLabel"))
        self.label_space2.setText(_translate("MainWindow", "TextLabel"))
        self.label_space1.setText(_translate("MainWindow", "TextLabel"))
        self.comboBox_baud.setItemText(0, _translate("MainWindow", "4800"))
        self.comboBox_baud.setItemText(1, _translate("MainWindow", "9600"))
        self.comboBox_baud.setItemText(2, _translate("MainWindow", "57600"))
        self.comboBox_baud.setItemText(3, _translate("MainWindow", "115200"))
        self.comboBox_data.setItemText(0, _translate("MainWindow", "5"))
        self.comboBox_data.setItemText(1, _translate("MainWindow", "6"))
        self.comboBox_data.setItemText(2, _translate("MainWindow", "7"))
        self.comboBox_data.setItemText(3, _translate("MainWindow", "8"))
        self.comboBox_check.setItemText(0, _translate("MainWindow", "N"))
        self.comboBox_check.setItemText(1, _translate("MainWindow", "O"))
        self.comboBox_check.setItemText(2, _translate("MainWindow", "E"))
        self.comboBox_stop.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_stop.setItemText(1, _translate("MainWindow", "1.5"))
        self.comboBox_stop.setItemText(2, _translate("MainWindow", "2"))
        self.label_main_id.setText(_translate("MainWindow", "TextLabel"))
        self.label_serial_id.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "参数设置与调整 "))
        self.menu.setTitle(_translate("MainWindow", "操作"))
        self.menu_2.setTitle(_translate("MainWindow", "帮助"))
        self.menu_3.setTitle(_translate("MainWindow", "关于"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_sysm.setText(_translate("MainWindow", "使用说明"))
        self.action_zzjs.setText(_translate("MainWindow", "作者介绍"))
        self.action_zlcx.setText(_translate("MainWindow", "指令查询"))
        self.action_set.setText(_translate("MainWindow", "配置参数"))
        self.action_sx.setText(_translate("MainWindow", "刷新"))
        self.action_alter_theme.setText(_translate("MainWindow", "更改主题"))
        self.action_data.setText(_translate("MainWindow", "打开数据路径"))
